spring:
  datasource:
    password: 1726
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    show-sql: true

